export const FETCH_MARKET_DATA_REQUEST = 'FETCH_MARKET_DATA_REQUEST';
export const FETCH_MARKET_DATA_FAILURE = 'FETCH_MARKET_DATA_FAILURE';
export const FETCH_MARKET_DATA_SUCCESS = 'FETCH_MARKET_DATA_SUCCESS';
export const SET_ASSET_FILTER = 'SET_ASSET_FILTER';
export const SET_UPDATED_MARKET_DATA = 'SET_UPDATED_MARKET_DATA';
export const SAVE_MARKET_ASSETS_INDEXES = 'SAVE_MARKET_ASSETS_INDEXES';
export const SET_SEARCH_ASSET_VALUE = 'SET_SEARCH_ASSET_VALUE';
export const SET_ASSETS_SHOW_MODE = 'SET_ASSETS_SHOW_MODE';