export const CONNECT_TO_WEBSOCKET = 'CONNECT_TO_WEBSOCKET';
export const DISCONNECT_FROM_WEBSOCKET_WITH_ERROR = 'DISCONNECT_FROM_WEBSOCKET_WITH_ERROR';
export const DISCONNECT_FROM_WEBSOCKET = 'DISCONNECT_FROM_WEBSOCKET';
export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';
export const SUCCESS_WEBSOCKET_CONNECTION = 'SUCCESS_WEBSOCKET_CONNECTION';
export const SUCCESS_WEBSOCKET_DISCONNECTION = 'SUCCESS_WEBSOCKET_DISCONNECTION';
export const MAKE_WEBSOCKET_ERROR = 'MAKE_WEBSOCKET_ERROR';